<a href="https://colab.research.google.com/github/Phoebe0222/deep-learning/blob/master/vectorization_and_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectorization in Python

Thanks to the package Numpy, vectorizing data has become so handy, and more importantly computing time has reduced greatrly comparing to using for loop. Following is the example from the course [Neural Networks and Deep Learning](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/ZPlX9/more-vectorization-examples), which has shown vectorization outruns for-loop in terms of computing time.

We want to calculate: 
\begin{equation}  
\sum_{i=1}^{1000000} a_i*b_i, where \  a_i \  and \  b_i \space are \  random \ numbers
\end{equation}






In [0]:
import time
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

#vectorization
tic = time.time()
c = np.dot(a,b) #transpose of a times b
toc = time.time()
print("Vectorized version:" + str(1000*(toc-tic)) + "ms" + " and c =" + str(c))

#for loop (explicit expression)
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i] 
toc = time.time()
print("for loop:" + str(1000*(toc-tic))+"ms"+ " and c =" + str(c))

Vectorized version:0.7493495941162109ms and c =250652.21687471058
for loop:458.0113887786865ms and c =250652.21687471532


So vectorization has reduced computing time greatly as shown above. Note that there are many other methods we can call on numpy other than the dot product of two vectors, such as exponential, logrithm etc. 

In [22]:
import numpy as np

n=100
u_zero = np.zeros((n,1))
v = np.random.rand(100)
u_exp = np.exp(v).reshape(100,1)
u_log = np.log(v)
u_ads = np.abs(v)
u_max = np.maximum(v,0.5)
u_sq = v**2
u_reci = 1/v

print(u_exp[0:5])
print(u_max[0:5])
print(np.dot(u_max,u_exp))

[[1.93149031]
 [2.01497048]
 [2.08274495]
 [1.26232461]
 [2.04198797]]
[0.65829189 0.70060455 0.73368671 0.5        0.71392383]
[112.77503669]


# Broadcasting
Another useful feature in Python is known as broadcasting. The general principle is as follow:

\begin{equation}  
Let \ A_{m,n} = 
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{pmatrix}
\end{equation}

and 
\begin{equation}  
\ B_{1,n} = 
 \begin{pmatrix}
  b_{1,1} & b_{1,2} & \cdots & b_{1,n} 
 \end{pmatrix}
\end{equation}

and
\begin{equation}  
\ C_{m,1} = 
 \begin{pmatrix}
  c_{1,1} \\
  c_{2,1}\\
  \vdots\\
  c_{m,1}
 \end{pmatrix}
\end{equation}
Then
\begin{equation}  
\ A_{m,n}+B_{1,n} = 
 \begin{pmatrix}
  a_{1,1} + b_{1,1} & a_{1,2} + b_{1,2} & \cdots & a_{1,n} + b_{1,n}  \\
  a_{2,1} + b_{1,1} & a_{2,2} + b_{1,2}  & \cdots & a_{2,n}+ b_{1,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1}  + b_{1,1}& a_{m,2} + b_{1,2}  & \cdots & a_{m,n}+ b_{1,n} 
 \end{pmatrix}
\end{equation}
and
\begin{equation}  
\ A_{m,n}+C_{m,1} = 
 \begin{pmatrix}
  a_{1,1} + c_{1,1} & a_{1,2} + c_{1,1} & \cdots & a_{1,n} + c_{1,1} \\
  a_{2,1} +  c_{2,1} & a_{2,2} + c_{2,1} & \cdots & a_{2,n}+  c_{2,1}\\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1}  +  c_{m,1}& a_{m,2} +  c_{m,1}  & \cdots & a_{m,n}+  c_{m,1}
 \end{pmatrix}
\end{equation}

Note that broadcasting also works for deduction, multiplication and division, but always always check  if thhe output is the desired one. Sometimes there might be matrix mismatch so the following are some examples on how to ensure the correct size of the matrix. 

In [33]:
import numpy as np

#create a rank 1 array, should avoid using
a = np.random.randn(5) 
print(a.shape)

#create a colunm vector
a = np.random.randn(5,1) 
print(a.shape)

#create a row vector
a = np.random.randn(1,5) 
print(a.shape)


(5,)
(5, 1)
(1, 5)
(5,)
[ 1.92944402 -0.04552309 -0.67826538 -0.08640671 -1.55323573]
